## Import libraries

In [187]:
import pandas as pd
import numpy as np
import re

## Import spotify dataset

In [188]:
spotify = pd.read_csv('../Datasets/data_spotify.csv')
spotify

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,valence,year
0,0.9950,['Carl Woitschach'],0.708,158648,0.1950,0,6KbQ3uYMLKb5jDxLF7wYDD,0.563000,10,0.1510,-12.428,1,Singende Bataillone 1. Teil,0,1928,0.0506,118.469,0.7790,1928
1,0.9940,"['Robert Schumann', 'Vladimir Horowitz']",0.379,282133,0.0135,0,6KuQTIu1KoTTkLXKrwlLPV,0.901000,8,0.0763,-28.454,1,"Fantasiestücke, Op. 111: Più tosto lento",0,1928,0.0462,83.972,0.0767,1928
2,0.6040,['Seweryn Goszczyński'],0.749,104300,0.2200,0,6L63VW0PibdM1HDSBoqnoM,0.000000,5,0.1190,-19.924,0,Chapter 1.18 - Zamek kaniowski,0,1928,0.9290,107.177,0.8800,1928
3,0.9950,['Francisco Canaro'],0.781,180760,0.1300,0,6M94FkXd15sOAOQYRnWPN8,0.887000,1,0.1110,-14.734,0,Bebamos Juntos - Instrumental (Remasterizado),0,1928-09-25,0.0926,108.003,0.7200,1928
4,0.9900,"['Frédéric Chopin', 'Vladimir Horowitz']",0.210,687733,0.2040,0,6N6tiFZ9vLTSOIxkj8qKrd,0.908000,11,0.0980,-16.829,1,"Polonaise-Fantaisie in A-Flat Major, Op. 61",1,1928,0.0424,62.149,0.0693,1928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169904,0.1730,"['DripReport', 'Tyga']",0.875,163800,0.4430,1,4KppkflX7I3vJQk7urOJaS,0.000032,1,0.0891,-7.461,1,Skechers (feat. Tyga) - Remix,75,2020-05-15,0.1430,100.012,0.3060,2020
169905,0.0167,"['Leon Bridges', 'Terrace Martin']",0.719,167468,0.3850,0,1ehhGlTvjtHo2e4xJFB0SZ,0.031300,8,0.1110,-10.907,1,Sweeter (feat. Terrace Martin),64,2020-06-08,0.0403,128.000,0.2700,2020
169906,0.5380,"['Kygo', 'Oh Wonder']",0.514,180700,0.5390,0,52eycxprLhK3lPcRLbQiVk,0.002330,7,0.1080,-9.332,1,How Would I Know,70,2020-05-29,0.1050,123.700,0.1530,2020
169907,0.0714,"['Cash Cash', 'Andy Grammer']",0.646,167308,0.7610,0,3wYOGJYD31sLRmBgCvWxa4,0.000000,1,0.2220,-2.557,1,I Found You,70,2020-02-28,0.0385,129.916,0.4720,2020
169908,0.1090,['Ingrid Andress'],0.512,214787,0.4280,0,60RFlt48hm0l4Fu0JoccOl,0.000000,0,0.1050,-7.387,1,More Hearts Than Mine,65,2020-03-27,0.0271,80.588,0.3660,2020

## Clean and transform spotify dataset for merge

In [189]:
x = spotify["artists"][0]
x

"['Carl Woitschach']"

In [190]:
re.sub(r"[^a-zA-Z0-9 ]","",x)

'Carl Woitschach'

In [191]:
def artist(x):
    x = re.sub(r"[^a-zA-Z0-9, ]","",x)
    return x

In [192]:
spotify["artists"]=spotify["artists"].apply(artist)

In [193]:
spotify["artists"] = spotify["artists"].apply(lambda x:x.casefold())
spotify["name"] = spotify["name"].apply(lambda x:x.casefold())

In [235]:
def name(x):
    x = re.sub(r"[^a-zA-Z0-9 ]","",x)
    x = x.replace(" remastered","")
    x = x.strip(" ")
    return x

In [236]:
spotify["name"] = spotify["name"].apply(name)

In [237]:
spotify

,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
0,carl woitschach,0.708,0.1950,0.563000,10,1,singende bataillone 1 teil,1928,118.469,0.7790,1928
1,"robert schumann, vladimir horowitz",0.379,0.0135,0.901000,8,1,fantasiestcke op 111 pi tosto lento,1928,83.972,0.0767,1928
2,seweryn goszczyski,0.749,0.2200,0.000000,5,0,chapter 118 zamek kaniowski,1928,107.177,0.8800,1928
3,francisco canaro,0.781,0.1300,0.887000,1,0,bebamos juntos instrumental remasterizado,1928-09-25,108.003,0.7200,1928
4,"frdric chopin, vladimir horowitz",0.210,0.2040,0.908000,11,1,polonaisefantaisie in aflat major op 61,1928,62.149,0.0693,1928
...,...,...,...,...,...,...,...,...,...,...,...
169904,"dripreport, tyga",0.875,0.4430,0.000032,1,1,skechers feat tyga remix,2020-05-15,100.012,0.3060,2020
169905,"leon bridges, terrace martin",0.719,0.3850,0.031300,8,1,sweeter feat terrace martin,2020-06-08,128.000,0.2700,2020
169906,"kygo, oh wonder",0.514,0.5390,0.002330,7,1,how would i know,2020-05-29,123.700,0.1530,2020
169907,"cash cash, andy grammer",0.646,0.7610,0.000000,1,1,i found you,2020-02-28,129.916,0.4720,2020
169908,ingrid andress,0.512,0.4280,0.000000,0,1,more hearts than mine,2020-03-27,80.588,0.3660,2020

In [238]:
spotify.drop(["acousticness","duration_ms","explicit","id","liveness","loudness","popularity","speechiness"],axis=1,inplace=True)

KeyError: "['acousticness' 'duration_ms' 'explicit' 'id' 'liveness' 'loudness'\n 'popularity' 'speechiness'] not found in axis"

In [239]:
spotify

,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
0,carl woitschach,0.708,0.1950,0.563000,10,1,singende bataillone 1 teil,1928,118.469,0.7790,1928
1,"robert schumann, vladimir horowitz",0.379,0.0135,0.901000,8,1,fantasiestcke op 111 pi tosto lento,1928,83.972,0.0767,1928
2,seweryn goszczyski,0.749,0.2200,0.000000,5,0,chapter 118 zamek kaniowski,1928,107.177,0.8800,1928
3,francisco canaro,0.781,0.1300,0.887000,1,0,bebamos juntos instrumental remasterizado,1928-09-25,108.003,0.7200,1928
4,"frdric chopin, vladimir horowitz",0.210,0.2040,0.908000,11,1,polonaisefantaisie in aflat major op 61,1928,62.149,0.0693,1928
...,...,...,...,...,...,...,...,...,...,...,...
169904,"dripreport, tyga",0.875,0.4430,0.000032,1,1,skechers feat tyga remix,2020-05-15,100.012,0.3060,2020
169905,"leon bridges, terrace martin",0.719,0.3850,0.031300,8,1,sweeter feat terrace martin,2020-06-08,128.000,0.2700,2020
169906,"kygo, oh wonder",0.514,0.5390,0.002330,7,1,how would i know,2020-05-29,123.700,0.1530,2020
169907,"cash cash, andy grammer",0.646,0.7610,0.000000,1,1,i found you,2020-02-28,129.916,0.4720,2020
169908,ingrid andress,0.512,0.4280,0.000000,0,1,more hearts than mine,2020-03-27,80.588,0.3660,2020

In [240]:
spotify.drop_duplicates(inplace=True)
spotify

,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
0,carl woitschach,0.708,0.1950,0.563000,10,1,singende bataillone 1 teil,1928,118.469,0.7790,1928
1,"robert schumann, vladimir horowitz",0.379,0.0135,0.901000,8,1,fantasiestcke op 111 pi tosto lento,1928,83.972,0.0767,1928
2,seweryn goszczyski,0.749,0.2200,0.000000,5,0,chapter 118 zamek kaniowski,1928,107.177,0.8800,1928
3,francisco canaro,0.781,0.1300,0.887000,1,0,bebamos juntos instrumental remasterizado,1928-09-25,108.003,0.7200,1928
4,"frdric chopin, vladimir horowitz",0.210,0.2040,0.908000,11,1,polonaisefantaisie in aflat major op 61,1928,62.149,0.0693,1928
...,...,...,...,...,...,...,...,...,...,...,...
169904,"dripreport, tyga",0.875,0.4430,0.000032,1,1,skechers feat tyga remix,2020-05-15,100.012,0.3060,2020
169905,"leon bridges, terrace martin",0.719,0.3850,0.031300,8,1,sweeter feat terrace martin,2020-06-08,128.000,0.2700,2020
169906,"kygo, oh wonder",0.514,0.5390,0.002330,7,1,how would i know,2020-05-29,123.700,0.1530,2020
169907,"cash cash, andy grammer",0.646,0.7610,0.000000,1,1,i found you,2020-02-28,129.916,0.4720,2020
169908,ingrid andress,0.512,0.4280,0.000000,0,1,more hearts than mine,2020-03-27,80.588,0.3660,2020

## Import Chord dataset for merge

In [241]:
chords = pd.read_csv('../Datasets/Chords_clean.csv',index_col=0)
chords

,Artists,Songs,Rating,Votes,Level,A,A#,A#dim,A#m,A(maj),...,Gmaj,Gmaj7,Gmaj7/D,Go,Gsus,Gsus2,Gsus2/A,Gsus2/C,Gsus4,Gsus4/B
0,jeff buckley,hallelujah,4.87,39010,advanced,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,john legend,all of me,4.83,19766,advanced,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,ed sheeran,perfect,4.85,30548,advanced,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,passenger,let her go,4.84,16657,intermediate,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,jason mraz,im yours,4.74,11924,advanced,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,tracy chapman,fast car,4.81,583,advanced,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
995,the marshall tucker band,cant you see,4.80,1966,novice,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,creedence clearwater revival,fortunate son,4.65,457,intermediate,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,no doubt,dont speak,4.82,1147,advanced,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,alicia keys,no one,4.77,510,intermediate,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Remove chords columns

In [242]:
chords.drop(list(chords.columns[5:]),axis=1,inplace=True)

In [243]:
chords

                          Artists          Songs  Rating  Votes         Level
0                    jeff buckley     hallelujah    4.87  39010      advanced
1                     john legend      all of me    4.83  19766      advanced
2                      ed sheeran        perfect    4.85  30548      advanced
3                       passenger     let her go    4.84  16657  intermediate
4                      jason mraz       im yours    4.74  11924      advanced
..                            ...            ...     ...    ...           ...
994                 tracy chapman       fast car    4.81    583      advanced
995      the marshall tucker band   cant you see    4.80   1966        novice
997  creedence clearwater revival  fortunate son    4.65    457  intermediate
998                      no doubt     dont speak    4.82   1147      advanced
999                   alicia keys         no one    4.77    510  intermediate

[997 rows x 5 columns]

In [244]:
chords[chords.duplicated()==True]

Empty DataFrame
Columns: [Artists, Songs, Rating, Votes, Level]
Index: []

## Merge datasets

In [245]:
df = pd.merge(left=chords, how='left', left_on=["Artists","Songs"],right=spotify, right_on=["artists","name"])

In [246]:
df

,Artists,Songs,Rating,Votes,Level,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
0,jeff buckley,hallelujah,4.87,39010,advanced,jeff buckley,0.323,0.136,0.001190,0.0,1.0,hallelujah,1994,96.880,0.0828,1994.0
1,john legend,all of me,4.83,19766,advanced,john legend,0.422,0.264,0.000000,8.0,1.0,all of me,2013-08-30,119.930,0.3310,2013.0
2,ed sheeran,perfect,4.85,30548,advanced,ed sheeran,0.599,0.448,0.000000,8.0,1.0,perfect,2017-03-03,95.050,0.1680,2017.0
3,passenger,let her go,4.84,16657,intermediate,passenger,0.479,0.545,0.000000,7.0,1.0,let her go,2013-02-17,74.897,0.2430,2013.0
4,jason mraz,im yours,4.74,11924,advanced,jason mraz,0.686,0.457,0.000000,11.0,1.0,im yours,2008-05-13,150.953,0.7180,2008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,creedence clearwater revival,fortunate son,4.65,457,intermediate,creedence clearwater revival,0.640,0.663,0.008060,0.0,1.0,fortunate son,1969-11-02,132.770,0.6630,1969.0
1402,creedence clearwater revival,fortunate son,4.65,457,intermediate,creedence clearwater revival,0.628,0.565,0.069300,0.0,1.0,fortunate son,1976-01-01,132.302,0.5820,1976.0
1403,no doubt,dont speak,4.82,1147,advanced,no doubt,0.520,0.709,0.000018,5.0,0.0,dont speak,1995-10-10,76.039,0.5360,1995.0
1404,no doubt,dont speak,4.82,1147,advanced,no doubt,0.507,0.752,0.000021,5.0,0.0,dont speak,2003-01-01,76.071,0.5540,2003.0
1405,alicia keys,no one,4.77,510,intermediate,alicia keys,0.644,0.548,0.000009,1.0,0.0,no one,2007-11-09,90.042,0.1660,2007.0

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1406 entries, 0 to 1405
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artists           1406 non-null   object
 1   Songs             1406 non-null   object
 2   Rating            1406 non-null   float64
 3   Votes             1406 non-null   int64
 4   Level             1406 non-null   object
 5   artists           1115 non-null   object
 6   danceability      1115 non-null   float64
 7   energy            1115 non-null   float64
 8   instrumentalness  1115 non-null   float64
 9   key               1115 non-null   float64
 10  mode              1115 non-null   float64
 11  name              1115 non-null   object
 12  release_date      1115 non-null   object
 13  tempo             1115 non-null   float64
 14  valence           1115 non-null   float64
 15  year              1115 non-null   float64
dtypes: float64(9), int64(1), object(6)
memory usage: 186.7+ KB

In [248]:
df.drop_duplicates(inplace=True)

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1406 entries, 0 to 1405
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artists           1406 non-null   object
 1   Songs             1406 non-null   object
 2   Rating            1406 non-null   float64
 3   Votes             1406 non-null   int64
 4   Level             1406 non-null   object
 5   artists           1115 non-null   object
 6   danceability      1115 non-null   float64
 7   energy            1115 non-null   float64
 8   instrumentalness  1115 non-null   float64
 9   key               1115 non-null   float64
 10  mode              1115 non-null   float64
 11  name              1115 non-null   object
 12  release_date      1115 non-null   object
 13  tempo             1115 non-null   float64
 14  valence           1115 non-null   float64
 15  year              1115 non-null   float64
dtypes: float64(9), int64(1), object(6)
memory usage: 186.7+ KB

## NaN

In [250]:
df[df.loc[:,"artists"].isnull()==True]

,Artists,Songs,Rating,Votes,Level,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
29,goo goo dolls,iris,4.73,4071,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,the beatles,let it be,4.73,6192,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,john lennon,imagine,4.82,7567,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,eagles,hotel california,4.84,14227,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,misc cartoons,frozen let it go,4.79,3826,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1381,bob marley,one love people get ready,4.77,483,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,hillsong worship,mighty to save,4.48,90,novice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383,vanessa williams,colors of the wind,4.80,526,intermediate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1384,amanda seyfried,little house,4.87,331,novice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1388,tab,1446000,4.67,94,advanced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [264]:
for i in list(spotify[spotify['artists']=='the beatles']['name'].values):
    if 'let it be' in i:
        print(i)

let it be  2009
let it be  2009
let it be  2015
let it be  2009

In [266]:
spotify[spotify['name']=='hotel california']

,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
68215,jorge dominguez y su grupo super class,0.632,0.48,0.0,9,1,hotel california,1996,86.021,0.561,1996

### Duplicated

In [72]:
duplicated = df[df[["Artists","Songs","Rating","Votes","Level"]].duplicated()==True]
duplicated

,Artists,Songs,Rating,Votes,Level,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
5,jason mraz,im yours,4.74,11924,advanced,jason mraz,0.686,0.457,0.000000,11.0,1.0,im yours,2008-05-12,150.953,0.718,2008.0
7,elvis presley,cant help falling in love,4.86,18880,advanced,elvis presley,0.438,0.325,0.000005,2.0,1.0,cant help falling in love,2002-09-24,101.577,0.362,2002.0
9,ed sheeran,thinking out loud,4.84,11793,advanced,ed sheeran,0.781,0.445,0.000000,2.0,1.0,thinking out loud,2014-06-21,78.998,0.591,2014.0
11,coldplay,the scientist,4.87,10272,advanced,coldplay,0.560,0.442,0.000017,5.0,1.0,the scientist,2002-08-08,146.448,0.212,2002.0
14,bruno mars,when i was your man,4.87,13865,advanced,bruno mars,0.612,0.280,0.000000,0.0,1.0,when i was your man,2012-12-07,72.795,0.387,2012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329,cyndi lauper,true colors,4.55,154,advanced,cyndi lauper,0.386,0.145,0.000196,0.0,1.0,true colors,1986-10-14,171.630,0.262,1986.0
1334,the marshall tucker band,cant you see,4.80,1966,novice,the marshall tucker band,0.417,0.490,0.001100,7.0,1.0,cant you see,1997-01-01,164.125,0.536,1997.0
1335,the marshall tucker band,cant you see,4.80,1966,novice,the marshall tucker band,0.389,0.662,0.003930,7.0,1.0,cant you see,1975-08-01,82.033,0.520,1975.0
1337,creedence clearwater revival,fortunate son,4.65,457,intermediate,creedence clearwater revival,0.628,0.565,0.069300,0.0,1.0,fortunate son,1976-01-01,132.302,0.582,1976.0
1339,no doubt,dont speak,4.82,1147,advanced,no doubt,0.507,0.752,0.000021,5.0,0.0,dont speak,2003-01-01,76.071,0.554,2003.0

In [77]:
duplicated.sort_values(["Artists","Songs","Rating","Votes","Level","year"])

,Artists,Songs,Rating,Votes,Level,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
489,adele,hello,4.84,1218,intermediate,adele,0.481,0.451,0.000000,5.0,0.0,hello,2015-10-23,157.966,0.289,2015.0
692,adele,hello,4.85,2492,intermediate,adele,0.481,0.451,0.000000,5.0,0.0,hello,2015-10-23,157.966,0.289,2015.0
43,adele,rolling in the deep,4.30,1219,advanced,adele,0.730,0.770,0.000000,8.0,1.0,rolling in the deep,2010-11-30,104.948,0.507,2010.0
44,adele,rolling in the deep,4.30,1219,advanced,adele,0.727,0.760,0.000000,8.0,1.0,rolling in the deep,2014-08-25,104.941,0.540,2014.0
328,adele,rolling in the deep,4.53,534,intermediate,adele,0.730,0.770,0.000000,8.0,1.0,rolling in the deep,2010-11-30,104.948,0.507,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,tones and i,dance monkey,4.83,1478,advanced,tones and i,0.824,0.588,0.000104,6.0,0.0,dance monkey,2019-08-29,98.027,0.513,2019.0
315,toto,africa,4.82,1571,advanced,toto,0.671,0.373,0.000080,9.0,1.0,africa,1982-04-08,92.717,0.732,1982.0
790,twenty one pilots,heathens,4.83,2192,advanced,twenty one pilots,0.732,0.396,0.000036,4.0,0.0,heathens,2016-06-16,90.024,0.548,2016.0
967,vance joy,riptide,4.77,2401,advanced,vance joy,0.484,0.731,0.000000,1.0,1.0,riptide,2014-09-09,101.654,0.510,2014.0
17,vance joy,riptide,4.88,17074,advanced,vance joy,0.484,0.731,0.000000,1.0,1.0,riptide,2014-09-09,101.654,0.510,2014.0

In [75]:
chords[chords["Artists"]=="adele"]

    Artists                  Songs  Rating  Votes         Level
8     adele       someone like you    4.75   3099      advanced
29    adele    rolling in the deep    4.30   1219      advanced
49    adele       someone like you    4.84   9423  intermediate
56    adele     when we were young    4.87   6496      advanced
80    adele  make you feel my love    4.88   6623      advanced
174   adele  make you feel my love    4.85   4049      advanced
217   adele    rolling in the deep    4.79   2171      advanced
232   adele    rolling in the deep    4.53    534  intermediate
233   adele   set fire to the rain    4.76   1746      advanced
235   adele   set fire to the rain    4.64    268      advanced
239   adele              all i ask    4.85   1213      advanced
351   adele                  hello    4.84   1218  intermediate
409   adele         turning tables    4.80   1026      advanced
499   adele                  hello    4.85   2492  intermediate
685   adele                skyfall    4.45    174      advanced
708   adele                skyfall    4.81   1157      advanced
878   adele      chasing pavements    4.60    143      advanced
887   adele           one and only    4.84    363      advanced
915   adele      dont you remember    4.87    696      advanced
974   adele              all i ask    4.88    388      advanced

In [202]:
unique = duplicated.sort_values(["Artists","Songs","Rating","Votes","Level","year"],ascending=True)
unique

,Artists,Songs,Rating,Votes,Level,artists,danceability,energy,instrumentalness,key,mode,name,release_date,tempo,valence,year
489,adele,hello,4.84,1218,intermediate,adele,0.481,0.451,0.000000,5.0,0.0,hello,2015-10-23,157.966,0.289,2015.0
692,adele,hello,4.85,2492,intermediate,adele,0.481,0.451,0.000000,5.0,0.0,hello,2015-10-23,157.966,0.289,2015.0
43,adele,rolling in the deep,4.30,1219,advanced,adele,0.730,0.770,0.000000,8.0,1.0,rolling in the deep,2010-11-30,104.948,0.507,2010.0
44,adele,rolling in the deep,4.30,1219,advanced,adele,0.727,0.760,0.000000,8.0,1.0,rolling in the deep,2014-08-25,104.941,0.540,2014.0
328,adele,rolling in the deep,4.53,534,intermediate,adele,0.730,0.770,0.000000,8.0,1.0,rolling in the deep,2010-11-30,104.948,0.507,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,tones and i,dance monkey,4.83,1478,advanced,tones and i,0.824,0.588,0.000104,6.0,0.0,dance monkey,2019-08-29,98.027,0.513,2019.0
315,toto,africa,4.82,1571,advanced,toto,0.671,0.373,0.000080,9.0,1.0,africa,1982-04-08,92.717,0.732,1982.0
790,twenty one pilots,heathens,4.83,2192,advanced,twenty one pilots,0.732,0.396,0.000036,4.0,0.0,heathens,2016-06-16,90.024,0.548,2016.0
967,vance joy,riptide,4.77,2401,advanced,vance joy,0.484,0.731,0.000000,1.0,1.0,riptide,2014-09-09,101.654,0.510,2014.0
17,vance joy,riptide,4.88,17074,advanced,vance joy,0.484,0.731,0.000000,1.0,1.0,riptide,2014-09-09,101.654,0.510,2014.0